### PR TITLE
fix: entropy plugin exec and remove legacy plugin handling

### LINKED ISSUE #559: Validate Entropy plugin execution

### LINKED ISSUE #579: HC core + SDK outbound gRPC requests not chunked
Code was written originally to assemble multi-chunk messages into one message, but not to detect large outbound messages and chunk them.

### PR DESCRIPTION
**Pull request by j-lanson**
Resolves #559 . Resolves #579 .

Updates `entropy` plugin to run smoothly, and also rips out the `MITRE_LEGACY_PLUGINS` infrastructure from Hipcheck core, as after this there are no more legacy plugin implementations.

Separate commit adds outbound chunking to hipcheck core and SDK, which was not previously implemented causing too-large gRPC messages to crash the analysis.

Also replaces a lot of `println/eprintln` calls with `log::{warn, error, trace, debug}`

### CODE REVIEW

**Comment by patrickjcasey** [comment]
I am starting to review this right now! It seems like `config/Hipcheck.kdl` needs to be updated to provide a manifest path for the entropy plugin

**Comment by j-lanson** [comment]
> I am starting to review this right now! It seems like `config/Hipcheck.kdl` needs to be updated to provide a manifest path for the entropy plugin

@patrickjcasey Good catch, I've updated the file

**Comment by patrickjcasey** [comment]
I am seeing this error when running this branch on the hipcheck repo with the default policy file

image

**Comment by j-lanson** [comment]
> I am seeing this error when running this branch on the hipcheck repo with the default policy file

As per the PR message, this branch needs the git parser fixes Andrew was working on. Let me rebase off of main now that those fixes are merged.

**Review by mchernicoff — APPROVED** [review]

**Pull request merged**
