### PR TITLE
feat: add RFD describing proposed batched query feature

### LINKED ISSUE #502: Investigate and write RFD for batching plugin queries
Sometimes a plugin will want to make a query for each element in a collection. In some cases, this has the potential to be very costly from a performance standpoint, as each request is a separate gRPC call. We should augment the Hipcheck protobuf definition to include a message type for a "batched" request, so Hipcheck knows to unload each element from a vector and make the `query()` for each one individually.

Investigate how this would work, and prepare an RFD describing the proposed change.

### PR DESCRIPTION
**Pull request by j-lanson**
Resolves #502 .

### CODE REVIEW

**Comment by alilleybrinker** [comment]
Thanks for this! Two comments:

- On the SDK changes, I think it should be possible to still have a single `query` function which uses a new trait to permit calling it with some a singular `&'static str` and `&[&'static str]` (or anything that derefs to that).
- Could the submit chunking actually be split into a separate RFD? It can be a small one. I'd view this as an oversight in the original design, I just think putting it here may make it hard to find later.

**Review by alilleybrinker — CHANGES_REQUESTED** [review]
(Sorry, forgot to give my comments as a review: see my comments above)

**Comment by j-lanson** [comment]
> * On the SDK changes, I think it should be possible to still have a single `query` function which uses a new trait to permit calling it with some a singular `&'static str` and `&[&'static str]` (or anything that derefs to that).

Can you elaborate on this point? As I understand, you're suggesting not having an explicit `batch_query()` function. I think interpreting whether a user wants to batch or not dependent on the type of the passed variable is wrong, because there may be some query endpoints that still take a `Vec` of objects. `query(Vec<Value>)` means "send this as a single request to the endpoint", `batch_query(Vec<Value>)` means "I don't want to waste time sending `hc` core each value individually, but they each represent a different query to X plugin"

**Comment by alilleybrinker** [comment]
> > * On the SDK changes, I think it should be possible to still have a single `query` function which uses a new trait to permit calling it with some a singular `&'static str` and `&[&'static str]` (or anything that derefs to that).
> 
> Can you elaborate on this point? As I understand, you're suggesting not having an explicit `batch_query()` function. I think interpreting whether a user wants to batch or not dependent on the type of the passed variable is wrong, because there may be some query endpoints that still take a `Vec` of objects. `query(Vec<Value>)` means "send this as a single request to the endpoint", `batch_query(Vec<Value>)` means "I don't want to waste time sending `hc` core each value individually, but they each represent a different query to X plugin"

Ah, you're right. Another thought though has occurred to me. It may be useful to, in addition to a singular `batch_query` method, also expose a `batch()` method which returns a handle with its own `query()` method, with the handle being consumed and the query sent with a `send()` (or some similar name) final method.

**Comment by j-lanson** [comment]
I added to the proposed `PluginEngine` interface changes to include the `batch()` function, and split the Submit chunking proposal into its own RFD

**Review by alilleybrinker — APPROVED** [review]
LGTM! :tada:

**Pull request merged**
