### PR TITLE
chore: Creates general `http` module for making requests

### PR DESCRIPTION
**Pull request by mchernicoff**
Resolves issue #98.

Moves code for creating authenticated agents for http requests into its own `http` module, in case we want to use that code for something other than making requests to the GitHub API.

This module includes a new, separate function for constructing `ureq` `Agents` with TLS using native system certificates. Even parts of our code that do not need authenticated `Agents` now use this function to make sure we are using the same TLS settings everywhere in Hipcheck.

### CODE REVIEW

**Comment by mchernicoff** [comment]
This is one possible way to handle Issue #98. Happy to take suggestions for other ways to do this.

**Review by j-lanson — APPROVED** [review]
Looks good!

**Comment by alilleybrinker** [comment]
@mchernicoff, LGTM! Anything keeping this marked as a draft?

**Comment by mchernicoff** [comment]
@alilleybrinker Just me making sure this was what we were looking to do. Fine to merge as is.

**Pull request merged**
