### PR TITLE
feat: add `hc cache` subcommand for manually listing/deleting elements of the cache

### PR DESCRIPTION
**Pull request by j-lanson**
This PR contributes to #182 . 

It introduces the `hc cache` command which allows controlled listing/deleting of cache entries (rooted in the `HC_CACHE` path resolved by the standard CLI).

**This PR does not currently take measures to short-cut dir-size calculation, so each operation can take multiple seconds to complete.** It should be discussed whether this is important enough to require before this PR is merged or can be addressed subsequently. 

`cli.rs` - changes to introduce the subcommand.
`main.rs` - call `cmd_cache()` function when CLI dictates
`cache.rs` - supporting types and the `HcCache` object itself, with public-facing functions for listing/deleting entries.

### CODE REVIEW

**Comment by alilleybrinker** [comment]
Reviewing now!

**Comment by alilleybrinker** [comment]
Okay, overall I really like this! I think the operations make sense and the listing UI is really clear.

For deletion, I think the following flag structure would make sense, improve the docs, and improve the compositionality of the options:

- `-f`/`--filter <PATTERN>`: Filter packages to delete based on pattern. This reduces the packages selected by any `--strategy` or `--max` provided.
- `-x`/`--execute`: Actually run the deletion instead of saying which ones _would_ be deleted. (dry run by default)
- `-s`/`--strategy <STRATEGY>`: `largest`, `smallest`, `oldest`, `newest`, `alpha` (alphabetical), `ralpha` (reverse alphabetical), `all`, `none`. Defaults to `none`.
- `-m`/`--max <N>`: Max number of entries to delete. Default varies based on strategy if left unspecified. `largest`/`smallest`/`oldest`/`newest` all default 1. `alpha` and `none` defaults to 0, `all` defaults to no limit.

This would be instead of the more subcommand based options so far. Now this _does_ mean that the user could create some nonsensical combinations which would need to be rejected. Some examples of good and bad:

```sh
$ hc cache delete # Deletes nothing, warns the user that no packages were selected and nothing was done.
$ hc cache delete -x # Not a dry run, but doesn't delete anything. Warns the user.
$ hc cache delete -s oldest --max 2 # Dry-run delete the 2 oldest in the cache.
$ hc cache delete -s oldest -x # Actually delete the 1 oldest.
$ hc cache delete -s alpha -m 1 -x # Actually delete the first alphabetical package
```

@j-lanson what do you think?

**Review by alilleybrinker — CHANGES_REQUESTED** [review]
Forgot to submit a review. Logging a "Request Changes" review just to show not to merge yet.

**Comment by j-lanson** [comment]
> * `-f`/`--filter <PATTERN>`: Filter packages to delete based on pattern. This reduces the packages selected by any `--strategy` or `--max` provided.
> * `-x`/`--execute`: Actually run the deletion instead of saying which ones _would_ be deleted. (dry run by default)
> * `-s`/`--strategy <STRATEGY>`: `largest`, `smallest`, `oldest`, `newest`, `alpha` (alphabetical), `ralpha` (reverse alphabetical), `all`, `none`. Defaults to `none`.
> * `-m`/`--max <N>`: Max number of entries to delete. Default varies based on strategy if left unspecified. `largest`/`smallest`/`oldest`/`newest` all default 1. `alpha` and `none` defaults to 0, `all` defaults to no limit.

I personally find that this is way more complicated and likely to cause confusion for users.
1. The syntax of `cache list` and `cache delete` is different, unless you intend for `cache list` to copy the same syntax, but it wasn't clear in your comment. If not, this makes the usage immediately less intuitive.
2. The fact that the syntax of `cache list/delete` is the same currently, there isn't a need for the concept of a "dry run" because one can run `cache list` with one set of qualifiers, see what would be printed, and if they want to delete those, they just change to using the `delete` subcommand. The difference between a "dry run" and a "listing" is very limited in my mind.
3. It seems unintuitive why `alpha` would default to deleting none but the others would default to 1
4. The current CLI was designed to have syntax as close as possible to English, so users wouldn't have to constantly reference the help menu for flag usage. `hc cache delete oldest 2`, `hc cache delete all` `hc cache delete hipcheck` are all very obvious to replicate once you have done it once. On this point, removing `--invert` and adding `smallest`, `newest`, `ralpha` would be a good takeaway from your proposal to pull into the existing CLI.

That being said, I defer to your judgement on the matter and if you still prefer your proposal, I'm totally okay refactoring the PR.

**Comment by alilleybrinker** [comment]
Okay, I've been thinking about this some more. First, I'll note that two other tools I looked at for prior art around handling deletion operations don't offer any flexibility beyond picking individual ones to delete, or using `--all` to delete all of them.

1. `docker image rm`: https://docs.docker.com/reference/cli/docker/image/rm/
2. `gh cache delete`: https://cli.github.com/manual/gh_cache_delete

The [CLI Guidelines](https://clig.dev/#arguments-and-flags) recommend "confirm[ing] before anything dangerous" and give some examples, including the dry-run/execute pattern I suggested above.

I'll also refer to the Oxide & Friends podcast episode, ["Rebooting a datacenter: A decade later"](https://oxide.computer/podcasts/oxide-and-friends/1935437) which details a story from Joyent about an engineer accidentally rebooting all hosts in an entire datacenter, in part because of a misleading CLI for a destructive operation (rebooting).

---

This is all just a collection of prior art, which still leaves the question of what we should do. As I see it, I don't think the currently-implemented approach of specifying a strategy and a number is quite right. `clap`'s handling of subcommands means that the full documentation for this API is hidden under additional `-h/`--help` invocations on the individual subcommands themselves, which means the help text isn't as informative as it could be.

As an MVP, we could implement something like the Docker and GitHub CLI examples above, permitting specifying individual cache entries to delete, or use an `--all` flag (or perhaps `--strategy all`, for forward compatibility with more strategies) to delete everything. This gives us more time to figure out how to shape this interface.

**Comment by j-lanson** [comment]
Consider:

`list --strategy/-s <STRAT> [--max/-m <N>[ [--filter/-f <PATTERN>]`
where strat: `oldest, newest, largest, smallest, alpha, ralpha`

`delete --strategy/-s <STRAT> --filter/-f <PATTERN> --force`
where strat: `all OR {oldest, alpha, smallest, ...} <N>`

the distinction here is that a sorting policy can be applied to `list` without a quantity `<N>`, but for `delete` it doesn't make sense to provide a sorting policy without a quantity.

`delete -s all`, `delete -s oldest 3`, `delete -s oldest` would all be valid, where the last would default to `oldest 1`. this would require us to do custom `clap` post-processing on the delete strategy but it does away with most of the nonsensical combinations.

we would put cache entry deletion at `MILD` from the CLI guidelines, so default behavior is to prompt `are you sure? y/n` when doing a `delete` operation, which can be skipped when `--force` is added.

**Comment by alilleybrinker** [comment]
> Consider:
> 
> `list --strategy/-s <STRAT> [--max/-m <N>[ [--filter/-f <PATTERN>]` where strat: `oldest, newest, largest, smallest, alpha, ralpha`
> 
> `delete --strategy/-s <STRAT> --filter/-f <PATTERN> --force` where strat: `all OR {oldest, alpha, smallest, ...} <N>`
> 
> the distinction here is that a sorting policy can be applied to `list` without a quantity `<N>`, but for `delete` it doesn't make sense to provide a sorting policy without a quantity.
> 
> `delete -s all`, `delete -s oldest 3`, `delete -s oldest` would all be valid, where the last would default to `oldest 1`. this would require us to do custom `clap` post-processing on the delete strategy but it does away with most of the nonsensical combinations.
> 
> we would put cache entry deletion at `MILD` from the CLI guidelines, so default behavior is to prompt `are you sure? y/n` when doing a `delete` operation, which can be skipped when `--force` is added.

I like this! Too bad that `clap` doesn't support it natively, but I think this seems like a good way to go. Thanks Julian!

**Review by alilleybrinker — CHANGES_REQUESTED** [review]
The error message if I omit the `--strategy` flag on `delete` doesn't make clear that I need to include the flag. Can you update the error message?

**Comment by alilleybrinker** [comment]
Otherwise really like this!

**Review by alilleybrinker — APPROVED** [review]

**Pull request merged**
